name: Build and release

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:
  workflow_call:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Install MinGW-w64
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64
    
      - name: publish-windows
        run: x86_64-w64-mingw32-g++ *.cpp -o tamagotchi-game.exe
    
      - name: publish-linux
        run: g++ *.cpp -o tamagotchi-game -O3

      - name: get date/date 
        env:
          TZ: "America/Chicago"
        run: | 
          echo "NOW=$(date +'%m-%d-%Y-%I.%M.%S.%p')" >> $GITHUB_ENV
       
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false    
          tag_name: ${{ env.NOW }}
          body: ${{ github.event.head_commit.message }}
          files: ${{ github.workspace }}/tamagotchi-game.exe, ${{ github.workspace }}/tamagotchi-game
          name: "Release ${{ env.NOW }}"
   
        

        
        