name: Build and release

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  workflow_dispatch:
  workflow_call:

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
       
      - name: publish-windows
        run: x86_64-w64-mingw32-g++ *.cpp -o tamagotchi-game.exe
    
      - name: publish-linux
        run: g++ *.cpp -o tamagotchi-game -O3

       
      - name: Upload Release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false    
          tag_name: ${{ env.NOW }}
          body: ${{ github.event.head_commit.message }}
          files: ${{ github.workspace }}/tamagotchi-game.exe, ${{ github.workspace }}/tamagotchi-game
          name: "Release ${{ env.NOW }}"
   
        

        
        